# Generated by Django 4.2.1 on 2023-05-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('employee_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='IMS_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_tag', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_app.employeedetail')),
                ('product_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_app.product')),
            ],
        ),
    ]
