# Generated by Django 4.2.1 on 2023-05-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0002_alter_employeedetail_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeproduct',
            old_name='date',
            new_name='issue_date',
        ),
    ]
