# Generated by Django 4.2.1 on 2023-05-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0003_rename_date_employeeproduct_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
