# Generated by Django 4.2.1 on 2023-05-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0005_employeedetail_designation_employeeproduct_assign_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='employeedetail',
            old_name='department',
            new_name='team',
        ),
    ]
